export default [
  {
    title: 'Population Zero',
    slug: 'population-zero',
    developer: 'Rockstar Games',
    img: 'https://i.imgur.com/Wbk7IgR.png',
    price: 235,
    promotionalPrice: 215,
  },
  {
    title: 'Population Zero',
    slug: 'population-zero',
    developer: 'Rockstar Games',
    img: 'https://i.imgur.com/n49XB78.png',
    price: 235,
    promotionalPrice: 215,
  },
  {
    title: 'Population Zero',
    slug: 'population-zero',
    developer: 'Rockstar Games',
    img: 'https://i.imgur.com/Ug0HjRo.png',
    price: 235,
    promotionalPrice: 215,
  },
  {
    title: 'Population Zero',
    slug: 'population-zero',
    developer: 'Rockstar Games',
    img: 'https://i.imgur.com/7ova9KM.png',
    price: 235,
    promotionalPrice: 215,
  },
  {
    title: 'Population Zero',
    slug: 'population-zero',
    developer: 'Rockstar Games',
    img: 'https://i.imgur.com/q1E3NnO.png',
    price: 235,
    promotionalPrice: 215,
  },
  {
    title: 'Population Zero',
    slug: 'population-zero',
    developer: 'Rockstar Games',
    img: 'https://i.imgur.com/GzoqQHk.png',
    price: 235,
    promotionalPrice: 215,
  },
]
