parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2020  # ou "latest" se preferir a versão mais recente
  sourceType: module
  ecmaFeatures:
    jsx: true  # se você estiver usando JSX

env:
  browser: true
  node: true
  es2021: true

extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "plugin:@next/next/recommended"
  - "plugin:storybook/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "next/core-web-vitals"
  - "next/typescript"

plugins:
  - "prettier"
  - "import"
  - "react"
  - "@typescript-eslint"

rules:
  prettier/prettier: "off"
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/no-empty-object-type": "off"
  "@typescript-eslint/no-unused-expressions": "off"
  "react/react-in-jsx-scope": "off"
  "@typescript-eslint/no-explicit-any": "off"
  "react/prop-types": "off"
  "@typescript-eslint/ban-types": "off"
  "@typescript-eslint/no-unsafe-function-type": "off"
  "@typescript-eslint/no-unused-vars": "off"
  "import/no-anonymous-default-export": "off"
